development:
  adapter: "mysql2"
  host: "database"
  port: "3306"
  username: "root"
  password: "redmine"
  database: "redmine_development"

test:
  adapter: "mysql2"
  host: "database"
  port: "3306"
  username: "root"
  password: "redmine"
  database: "redmine_test"
