version: "3"

services:
  redmine:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: "redmine-tracky"
    restart: always
    command: >
      bash -c "bundle &&
           bundle exec rails db:prepare &&
           bundle exec rake redmine:plugins:migrate &&
           rm -f tmp/pids/server.pid &&
           bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - "database"
    ports:
      - "3000:3000"
    networks:
      - base
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3000"]
        interval: 30s
        timeout: 10s
        retries: 10
    environment:
      RAILS_ENV: development
      REDMINE_SECRET_KEY_BASE: BfHuEvT6
    volumes:
      - plugin_link:/usr/src/redmine/plugins/redmine_tracky
    depends_on:
      database:
        condition: service_healthy
    links:
      - database:database

  database:
    image: mariadb:10.6.4
    container_name: "redmine-database"
    restart: always
    networks:
      - base
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: redmine
      MYSQL_DATABASE: "redmine_${CONTAINER_ENV}"
    volumes:
      - ./.data/mysql:/var/lib/mysql

networks:
  base:
    driver: bridge

volumes:
  plugin_link:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${PLUGIN_PATH}"
