name: Enable auto-merge for security upgrades
on:
  pull_request_target:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  depfu:
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for security labeled PRs
        if: ${{ contains(github.event.pull_request.labels.*.name, 'security') }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
