name: validation

on: push

jobs:
  test_ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Redmine
        uses: actions/checkout@v4
        with:
          repository: redmine/redmine
          path: redmine

      - name: Checkout Tracky
        uses: actions/checkout@v4
        with:
          repository: renuo/redmine_tracky
          path: redmine/plugins/redmine_tracky

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'

      - name: Start MySQL and update gems
        run: gem update --system && sudo service mysql start

      - name: Setup Tracky
        run: cd redmine/plugins/redmine_tracky && ./bin/setup
        env:
          GITHUB_ACTIONS: true

      - name: Lint
        run: cd redmine/plugins/redmine_tracky && rake lint_ruby

      - name: Run tests
        run: cd redmine && rake test TEST=plugins/redmine_tracky

  check_javascript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install node modules
        working-directory: ./assets.src
        run: npm install

      - name: Lint
        run: rake lint_javascript
