name: validation
on:
  - push
jobs:
  test_ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.2"
      - name: Setup Redmine
        run: make && rake install_dependencies
      - name: Install gems
        run: BUNDLE_GEMFILE=PluginGemfile bundle install; gem install rubocop; 
      - name: Lint
        run: bundle exec rubocop -c .rubocop.yml
      - name: Run tests
        run: BUNDLE_GEMFILE=PluginGemfile bundle exec rake test_ruby
  check_javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install node packages
        working-directory: ./assets.src
        run: npm install
      - name: Lint
        working-directory: ./assets.src
        run: npm run lint
