name: validation

on: push

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redmine-version: ['5.1-stable', '6.0-stable']
    steps:
      - name: Checkout Redmine
        uses: actions/checkout@v4
        with:
          repository: redmine/redmine
          ref: ${{ matrix.redmine-version }}

      - name: Checkout Tracky
        uses: actions/checkout@v4
        with:
          repository: renuo/redmine_tracky
          path: plugins/redmine_tracky

      - name: Cache gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: gems-${{ hashFiles('Gemfile', 'plugins/redmine_tracky/PluginGemfile.lock') }}-${{ matrix.redmine-version }}

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: plugins/redmine_tracky/assets.src/node_modules
          key: npm-${{ hashFiles('plugins/redmine_tracky/assets.src/package-lock.json') }}-${{ matrix.redmine-version }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.7'
          bundler-cache: true

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Start MySQL
        run: sudo service mysql start

      - name: Setup Tracky
        working-directory: plugins/redmine_tracky
        run: bin/setup
        env:
          GITHUB_ACTIONS: true

      - name: Run linters
        working-directory: plugins/redmine_tracky
        run: bundle exec rake lint

      - name: Run tests
        working-directory: plugins/redmine_tracky
        run: bundle exec rake test
        env:
          GITHUB_ACTIONS: true

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() # Always run even if the previous step fails
        with:
          report_paths: 'test/reports/TEST-*.xml'
